accounts/urls.py
from django.conf.urls import url
from .views import * # . will look into docs with the name views in this file this 

urlpatterns =[
 	url(r'^$', home, name="index"),
    url(r'^login/$', LogIn, name="login"),
    url(r'^signup/$', SignUp, name="signup"),
    url(r'^logout/$', Logout, name="logout"),
]

tutorial/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('accounts.urls', namespace='home')),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin



class UserManager(BaseUserManager, models.Manager):

    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):

        if not email:
            raise ValueError('El email debe ser obligatorio')
        email = self.normalize_email(email)

        user = self.model(email=email,
                          is_active=True, is_staff=is_staff,
                          is_superuser=is_superuser, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(
            email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(
            email, password, True, True, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin, models.Model):

    # unique, no se van a repetir
    id = models.AutoField(primary_key=True, unique=True)

    nombre = models.CharField(max_length=40)
    apaterno = models.CharField(max_length=25)
    email = models.CharField(unique=True, max_length=50)
    genero = models.CharField(
        choices=(('M', 'Mujer'), ('H', 'Hombre')), max_length=16)
    descripcion = models.TextField()

    # intermediario entre trans de cada modelo, object managaer de cada modelo
    objects = UserManager()

    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'

    def get_short_name(self):
        return self.nombre

accounts/forms.py
from django import forms
from .models import *


class SignupForm(forms.Form):

    email = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "correo@gmail.com"
            }
        )
    )

    nombre = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "nombre"
            }
        )
    )

    apaterno = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Apellido"
            }
        )
    )

    descripcion = forms.CharField(
        max_length=300,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "descripcion"
            }
        )
    )
    GENDER_CHOICES = (
        ('M', 'Mujer'),
        ('H', 'Hombre')
    )
    genero = forms.CharField(
        required=True,
        widget=forms.Select(
            attrs={
                "class": "form-control",
                "placeholder": "descripcion"
            },  
            choices=GENDER_CHOICES
        )
    )

    password = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "password"
            }
        )
    )
    confirm_password = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "confirm password"
            }
        )
    )


def clean(self):
    cleaned_data = super(SignupForm, self).clean()
    pasword = cleaned_data.get("password")
    confirm_password = cleaned_data.get("confirm_password")
    if password != confirm_password:
        raise forms.ValidationError(
            "password and confirm password must be the same (they are not right now...)!"
        )


class LoginForm(forms.Form):

    email = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "correo@gmail.com"
            }
        )
    )

    password = forms.CharField(
        max_length=100,
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
                "placeholder": "password"
            }
        )
    )

accounts/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect, HttpResponse
from .models import User
from .forms import *
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
import json


# Create your views here.
# here comes all de logic 
def home (request):
    if request.user.is_authenticated():
        genero = User.objects.get(email=request.user.email).genero
        usuarios = User.objects.filter(~Q(email=request.user.email,genero=genero))
        return render (request,'home.html', {'users':usuarios})
    else:
        return redirect('home:login')

def SignUp(request):

    form = SignupForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            form.cleaned_data.pop('confirm_password', None)
            user = User.objects.create_user(**form.cleaned_data)
            return redirect('home:index')
    else:
        return render(request, 'signup.html', {'form': form})

def LogIn(request):

    form = LoginForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['email'],
                password=form.cleaned_data['password']
            )
            if user is not None:
                login(request, user)
                return redirect('home:index')
            else:
                return HttpResponse("El usuario no existe en la BD!")
    else:
        return render(request, 'login.html', {'form': form})

def Logout(request):
    logout(request)
    return redirect('home:login')

templates/base.html
{%load static %}
<html>
	<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	{% block title%}
	
	{% endblock %}
	</head>
	<body>
		{% if request.user.is_authenticated %}
		    <h3>¡Hola {{request.user.username}}</h3>		
		{% endif %}
		<ul>
			<li class="active"><a href="{% url 'home:index' %}">Home</a></li>
			{% if not request.user.is_authenticated %}
			    <li><a href="{% url 'home:signup' %}">Sign up</a></li>
				<li><a href="{% url 'home:login' %}">Login</a></li>			
			{% else %}
			<li><a href="">Mi Perfil</a></li>
			<li><a href="{% url 'home:logout' %}">Logout</a></li>
			{% endif %}			
		</ul>
		{% block body %}
		{% endblock %}
	</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block head %}
<title>Home</title>
{% endblock %}
{% block body %}
	{% csrf_token %}
	<h3>Usuarios que no son tú (beeeeeeeeeeeee)</h3>
    {% for user in users %}  
        {{user}}
    {% endfor %}
{% endblock body %}

templates/login.html
{%  extends "base.html" %}
{% block title %}
    <h1>LogIn</h1>
{% endblock title %}

{% block body %}
    <div>  		
		<form action="{% url 'home:login' %}" method="POST">
			{% csrf_token %}
			{{form.non_field_errors}}
			<div class="form-group">
				{{form.email}}
			</div>
			<div class="form-group">
				{{form.password}}
			</div>
			<input type="submit" value="Login">
		</form>    		
    </div>
{% endblock body %}

templates/signup.html
{%  extends "base.html" %}
{% block title %}
    <h1>SignUp</h1>
{% endblock title %}

{% block body %}
	<form action="{% url 'home:signup' %}" method="POST">
		{% csrf_token %}
		{{form.non_field_errors}}					
		<div class="form-group">
			{{form.email}}
		</div>
		<div class="form-group">
			{{form.nombre}}
		</div>
        <div class="form-group">
            {{form.apaterno}}
        </div>
        <div class="form-group">
            {{form.descripcion}}
        </div>
        <div class="form-group">
            {{form.genero}}
        </div>
    	<div class="form-group">
			{{form.password}}
		</div>
		<div class="form-group">
			{{form.confirm_password}}
		</div>
		<div >
			<input type="submit" value="Registrar">
		</div>    					
	</form>
{% endblock body %}